### ISSUE TITLE
Anjay LWM2M | Arduino Library

### ISSUE THREAD

**Issue by bitvijays** [AVSystem/Anjay#39]
Dear Anjay LWM2M Team,

Hope you are doing well. Thank you for your awesome work on LWM2M. I was wondering if there's a way to compile the Anjay lwm2m library for the Arduino type devices? or a way to add the library via platformIO? Currently for lwm2m there's [OpenHab Wakaama](https://openhab-nodes.github.io/wakaamaNode/) which is build on top of [Eclipse Wakaama](https://github.com/eclipse/wakaama). However, both are kinda out-dated. 

Is there a way to compile for Arduino. If not, what would be the way to do it? I would be happy to help to create one. 

Let me know your thoughts.
Yours Sincerely,
Vijay

**Comment by kFYatek** [comment]
Most of the porting work that might be necessary is described in the [Porting guide for non-POSIX platforms](https://avsystem.github.io/Anjay-doc/PortingGuideForNonPOSIXPlatforms.html) in the documentation.

The biggest problem might be that the only currently supported way of compiling Anjay is to use CMake - if you can somehow integrate it in your Arduino build process, it should be possible to use Anjay on it, provided that the specific device has enough resources to run it.

We are currently in the process of refactoring the codebase so that compiling with alternative build systems will be much more straightforward. Most of the work is already done on our internal private branches. I think you can expect such release in early to mid March.

**Comment by kFYatek** [comment]
Sorry for not updating this issue earlier. Compiling with alternate, non-CMake build systems is now supported since version 2.3. Please open another issue if you still have problems with that.
