### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by mjjaniec** [AVSystem/Anjay#8]
Hi guys!
I've run into problems during Anjay installation.

First: `apt-get libmbedtls-dev` doesn't work for me. Potentially I have wrong configuration of apt-get, but I couldn't find any easy fix in google.  Please check it.

Second: In https://github.com/AVSystem/Anjay#quickstart-guide there is information that it's possible to use one of three DTLS libraries. So I wanted to try OpenSSL. Unfortunately I couldn't find how to select it in the guide nor in full documentation.
After awhile of reading of some source codes I managed to guess proper command which is:
`cmake . -DWITH_OPENSSL=true -DWITH_MBEDTLS=false`
Please put this information into quick start guide or at least into documentation.

**Comment by kFYatek** [comment]
`libmbedtls-dev` is present in Ubuntu since version 16.04 (Xenial). 16.04 is the current LTS release, and we think it is a reasonable requirement for a development machine. We have no plans to support older releases - it is of course possible to build Anjay on them, but you're on your own for finding and installing appropriate dependencies. Ubuntu is not likely to be a production target platform anyway, and for the more likely, embedded targets, you'll probably need a custom build of mbed TLS anyway.

As for documenting the process of selecting the DTLS backend - yes, you're right, we'll work on it.

**Comment by sznaider** [comment]
Resolved in version 1.3.0.
